DROP TABLE IF EXISTS film;
CREATE TABLE IF NOT EXISTS film (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    anno INT NOT NULL,
    genere VARCHAR(100) NOT NULL,
    rating DECIMAL(3,1) NOT NULL
);